version: '3.8'

services:
  compliance-agent:
    build: .
    container_name: compliance-agent-dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      # Mount source for development (remove in production)
      - ./src:/app/src:ro
      - ./main.py:/app/main.py:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: compliance-agent-network
